# ros_control_boilerplate Settings -----------------------





# Individual Position/Velocity Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
controller:
  # Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - base_link_left_joint
      - base_link_right_joint
      - arm_front_left_joint
      - arm_front_right_joint
      - arm_back_left_joint
      - arm_back_right_joint
      - track_front_left_joint
      - track_front_right_joint
      - track_back_left_joint
      - track_back_right_joint
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  # Position Controllers ---------------------------------------
  arm_front_left:
    type: effort_controllers/JointPositionController
    joint: arm_front_left_joint
    pid: {p: 200.0, i: 1.00, d: 10.0}
  arm_back_left:
    type: effort_controllers/JointPositionController
    joint: arm_back_left_joint
    pid: {p: 200.0, i: 1.00, d: 10.0}
  arm_front_right:
    type: effort_controllers/JointPositionController
    joint: arm_front_right_joint
    pid: {p: 200.0, i: 1.00, d: 10.0}
  arm_back_right:
    type: effort_controllers/JointPositionController
    joint: arm_back_right_joint
    pid: {p: 200.0, i: 1.00, d: 10.0}
  # Vilocity Controllers ---------------------------------------
  track_front_left:
    type: effort_controllers/JointVelocityController
    joint: track_front_left_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  track_back_left:
    type: effort_controllers/JointVelocityController
    joint: track_back_left_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  track_front_right:
    type: effort_controllers/JointVelocityController
    joint: track_front_right_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  track_back_right:
    type: effort_controllers/JointVelocityController
    joint: track_back_right_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}


# Group Position Controllers ---------------------------------------
# Allows to send single ROS msg of Float64MultiArray to all joints

